sudo: false

language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  include:
    # Current $required_php_version for WordPress: 5.2.4
    - php: 5.2
    - php: 5.6
    - php: 7.0
      env: WP_TRAVISCI=sniff
    - php: 7.0
      env: WP_TRAVISCI=codecoverage
    - php: hhvm

  allow_failures:
    - php: 'hhvm'

install:
  # Set up WordPress
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION


# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  # Install JSCS: JavaScript Code Style checker.
  # @link http://jscs.info/
  - if [[ "$WP_TRAVISCI" == "sniff" ]]; then npm install -g jscs; fi
  # Install JSHint, a JavaScript Code Quality Tool.
  # @link http://jshint.com/docs/
  - if [[ "$WP_TRAVISCI" == "sniff" ]]; then npm install -g jshint; fi
  # Install Composer
  - if [[ "$WP_TRAVISCI" == "codecoverage" ] || [ "$WP_TRAVISCI" == "sniff" ]] ; composer install --no-interaction; fi

script:
  # Search for PHP syntax errors.
  - find -L ./src/ -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
  # Run the theme through JSHint.
  - if [[ "$WP_TRAVISCI" == "sniff" ]]; then jshint .; fi
  # Run the theme through JavaScript Code Style checker.
  - if [[ "$WP_TRAVISCI" == "sniff" ]]; then jscs .; fi
  # WordPress Coding Standards.
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  - if [[ "$WP_TRAVISCI" == "sniff" ]]; then vendor/bin/phpcs -n --report=emacs --standard=phpcs.ruleset.xml src --extensions=php; fi
  # PHPUnit tests
  - if [ "$WP_TRAVISCI" == "codecoverage" ] || [ "$WP_TRAVISCI" == "sniff" ]; then composer install --no-interaction; fi

after_script:
  - if [[ "$WP_TRAVISCI" == "codecoverage" ]] ; then bash <(curl -s https://codecov.io/bash); fi

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: false
